runtime: nodejs16  # Verifique se esta versão é compatível e suportada
env: flex
entrypoint: npm start

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 20
  cpu_utilization:
    target_utilization: 0.5

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# As configurações de rede podem ser necessárias dependendo
